services:
  cat:
    image: ${API_IMAGE_PUBLIC}:git-${GIT_SHA}
    mem_limit: 256m
    cpus: 0.25
    restart: always

  dog:
    image: ${API_IMAGE_PUBLIC}:git-${GIT_SHA}
    mem_limit: 256m
    cpus: 0.25
    restart: always

  nginx:
    mem_limit: 128m
    cpus: 0.20
    restart: always

  prometheus:
    mem_limit: 512m
    cpus: 0.50
    restart: always

  grafana:
    mem_limit: 512m
    cpus: 0.50
    restart: always

  node-exporter:
    mem_limit: 128m
    cpus: 0.10
    restart: always

  cadvisor:
    mem_limit: 256m
    cpus: 0.25
    restart: always

  portainer:
    mem_limit: 256m
    cpus: 0.25
    restart: always
